#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'


require 'strscan'

module Rhcl
  class Parse < Racc::Parser

module_eval(<<'...end parse.y/module_eval...', 'parse.y', 98)

def initialize(obj)
  src = obj.is_a?(IO) ? obj.read : obj.to_s
  @ss = StringScanner.new(src)
end

def scan
  tok = nil
  in_comment = false

  until @ss.eos?
    if (tok = @ss.scan /\s+/)
      # nothing to do
    elsif (tok = @ss.scan(/#/))
      @ss.scan_until(/\n/)
    elsif (tok = @ss.scan(%r|/|))
      case @ss.getch
      when '/'
        @ss.scan_until(/(\n|\z)/)
      when '/'
        @ss.scan_until(%r{(\*/|\z)})
      else
        raise "comment expected, got '#{tok}'"
      end
    elsif (tok = @ss.scan(/\d+\.\d+/))
      yield [:FLOAT, tok.to_f]
    elsif (tok = @ss.scan(/\d+/))
      yield [:INTEGER, tok.to_i]
    elsif (tok = @ss.scan(/-/))
      yield [:MINUS, tok]
    elsif (tok = @ss.scan(/,/))
      yield [:COMMA, tok]
    elsif (tok = @ss.scan(/\=/))
      yield [:EQUAL, tok]
    elsif (tok = @ss.scan(/\[/))
      yield [:LEFTBRACKET, tok]
    elsif (tok = @ss.scan(/\]/))
      yield [:RIGHTBRACKET, tok]
    elsif (tok = @ss.scan(/\{/))
      yield [:LEFTBRACE, tok]
    elsif (tok = @ss.scan(/\}/))
      yield [:RIGHTBRACE, tok]
    elsif (tok = @ss.scan(/"/))
      yield [:STRING, (@ss.scan_until(/("|\z)/) || '').sub(/"\z/, '')]
    else
      identifier = (@ss.scan_until(/(\s|\z)/) || '').sub(/\s\z/, '')
      token_type = :IDENTIFIER

      if ['true', 'false'].include?(identifier)
        identifier = (identifier =~ /true/)
        token_type = :BOOL
      end

      yield [token_type, identifier]
    end
  end

  yield [false, '$end']
end
private :scan

def parse
  yyparse self, :scan
end

def self.parse(obj)
  self.new(obj).parse
end
...end parse.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    10,    29,     9,    30,    16,    17,    20,    14,     7,    31,
    21,    22,     3,   nil,    10,     6,    13,    28,     3,     6,
   nil,     6,    24,     3,     3,   nil,     6,     6,    26,    27 ]

racc_action_check = [
     9,    25,     3,    25,     9,     9,     9,     7,     1,    30,
     9,     9,     1,   nil,     5,     1,     5,    23,    23,     5,
   nil,    23,    10,    10,     0,   nil,    10,     0,    20,    20 ]

racc_action_pointer = [
    20,     8,   nil,    -3,   nil,    12,   nil,     7,   nil,    -2,
    19,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    19,   nil,   nil,    14,   nil,    -8,   nil,   nil,   nil,   nil,
    -1,   nil ]

racc_action_default = [
   -21,   -21,    -1,   -13,   -10,   -21,   -14,   -21,    -2,   -21,
   -21,   -11,   -12,   -13,    32,    -5,    -6,    -7,    -8,    -9,
   -21,   -19,   -20,   -21,    -4,   -21,   -16,   -17,    -3,   -15,
   -21,   -18 ]

racc_goto_table = [
     8,     1,    11,    15,    19,    12,    18,    25,   nil,   nil,
   nil,    23,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     8 ]

racc_goto_check = [
     2,     1,     3,     4,     5,     6,     3,     8,   nil,   nil,
   nil,     1,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     1,    -1,    -3,    -6,    -5,     0,   nil,   -13 ]

racc_goto_default = [
   nil,   nil,     2,   nil,   nil,   nil,     4,     5,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 15, :_reduce_1,
  2, 15, :_reduce_2,
  3, 17, :_reduce_3,
  2, 17, :_reduce_4,
  3, 16, :_reduce_5,
  3, 16, :_reduce_6,
  3, 16, :_reduce_7,
  3, 16, :_reduce_8,
  3, 16, :_reduce_9,
  1, 16, :_reduce_10,
  2, 20, :_reduce_11,
  2, 20, :_reduce_12,
  1, 21, :_reduce_13,
  1, 21, :_reduce_14,
  3, 19, :_reduce_15,
  2, 19, :_reduce_16,
  1, 22, :_reduce_17,
  3, 22, :_reduce_18,
  1, 18, :_reduce_19,
  1, 18, :_reduce_20 ]

racc_reduce_n = 21

racc_shift_n = 32

racc_token_table = {
  false => 0,
  :error => 1,
  :LEFTBRACE => 2,
  :RIGHTBRACE => 3,
  :IDENTIFIER => 4,
  :EQUAL => 5,
  :BOOL => 6,
  :STRING => 7,
  :LEFTBRACKET => 8,
  :RIGHTBRACKET => 9,
  :listitem => 10,
  :COMMA => 11,
  :INTEGER => 12,
  :FLOAT => 13 }

racc_nt_base = 14

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "LEFTBRACE",
  "RIGHTBRACE",
  "IDENTIFIER",
  "EQUAL",
  "BOOL",
  "STRING",
  "LEFTBRACKET",
  "RIGHTBRACKET",
  "listitem",
  "COMMA",
  "INTEGER",
  "FLOAT",
  "$start",
  "objectlist",
  "objectitem",
  "object",
  "number",
  "list",
  "block",
  "blockId",
  "listitems" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parse.y', 5)
  def _reduce_1(val, _values)
                    val[0]
               
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 9)
  def _reduce_2(val, _values)
                     val[0].merge(val[1])
               
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 14)
  def _reduce_3(val, _values)
                val[1]
          
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 18)
  def _reduce_4(val, _values)
                {}
          
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 23)
  def _reduce_5(val, _values)
                    {val[0] => val[2]}
              
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 27)
  def _reduce_6(val, _values)
                    {val[0] => val[2]}
              
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 31)
  def _reduce_7(val, _values)
                    {val[0] => val[2]}
              
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 35)
  def _reduce_8(val, _values)
                    {val[0] => val[2]}
              
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 39)
  def _reduce_9(val, _values)
                    {val[0] => val[2]}
              
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 43)
  def _reduce_10(val, _values)
                    val[0]
              
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 48)
  def _reduce_11(val, _values)
               {val[0] => val[1]}
         
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 52)
  def _reduce_12(val, _values)
               {val[0] => val[1]}
         
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 58)
  def _reduce_13(val, _values)
                 val[0]
           
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 62)
  def _reduce_14(val, _values)
                 val[0]
           
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 67)
  def _reduce_15(val, _values)
              val[1]
        
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 71)
  def _reduce_16(val, _values)
              []
        
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 76)
  def _reduce_17(val, _values)
                   [val[0]]
             
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 80)
  def _reduce_18(val, _values)
                   val[0] + [val[2]]
             
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 85)
  def _reduce_19(val, _values)
                val[0]
          
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 89)
  def _reduce_20(val, _values)
                val[0]
          
  end
.,.,

def _reduce_none(val, _values)
  val[0]
end

  end   # class Parse
  end   # module Rhcl
